# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Thing.create(name: "Spaghetti", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Spaghettata.JPG/270px-Spaghettata.JPG")
Thing.create(name: "Flatiron School", image_url: "https://crunchbase-production-res.cloudinary.com/image/upload/c_lpad,h_256,w_256,f_jpg/v1397752768/e4ce735bc7e299313e5ca95eaf86a030.png")
Thing.create(name: "Millard Fillmore", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Millard_Fillmore-Edit1.jpg/1200px-Millard_Fillmore-Edit1.jpg")
Thing.create(name: "Sinatra", image_url: "http://www.justwebframeworks.com/wp-content/uploads/2014/07/photo.jpg.png")
Thing.create(name: "Capybara(animal)", image_url: "http://animals.sandiegozoo.org/sites/default/files/2016-10/animals_hero_capybara.jpg")
Thing.create(name: "Locking Your Keys In Your Car", image_url: "http://replacecarkey.org/wp-content/uploads/2015/08/locked_keys_in_car.jpg")
Thing.create(name: "The Smell of Wet Dog", image_url: "https://static1.squarespace.com/static/53b1eedce4b0ea2f4d03027b/561fc123e4b0fc911f62badd/561fc124e4b039aec9b26b3a/1444921637056/%C2%A9SophieGamand-WetDog-Diamond-web.jpg?format=300w")
Thing.create(name: "The Great Mouse Detective", image_url: "http://vignette3.wikia.nocookie.net/bakerstreet/images/f/f6/Basil_the_great_mouse_detective3.jpg/revision/latest?cb=20130202230545")
Thing.create(name: "That Scene Where the Orc Goes 'Looks like meat's back on the menu, boys!", image_url: "https://i.ytimg.com/vi/R6PkDHuaXi8/maxresdefault.jpg")
Thing.create(name: "Borscht", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Borscht_served.jpg/1200px-Borscht_served.jpg")
Thing.create(name: "Umlauts", image_url: "http://www.k-international.com/wp-content/uploads/2017/05/Motorheadselftitled.jpg")

Thing.create(name: "The Eclipse", image_url: "https://i.redd.it/j62qq9wnw5hz.jpg")
Thing.create(name: "Pizza on Pineapple", image_url: "https://i.imgur.com/AQ3CnWD.png")
Thing.create(name: "That Rug With Roads On It", image_url: "https://images-na.ssl-images-amazon.com/images/I/51kaN2uyWzL.jpg")
Thing.create(name: "Dog Selfies", image_url: "https://i.redd.it/c46tqpy8rb5z.jpg")
Thing.create(name: "This Weird Cat Thing", image_url: "http://i3.kym-cdn.com/photos/images/newsfeed/001/077/564/d5b.jpg")
Thing.create(name: "A Sous Vide", image_url: "http://www.seriouseats.com/images/2015/06/20150610-sous-vide-chicken-guide-18.jpg")
Thing.create(name: "Square Cats", image_url: "https://i.imgur.com/8wq6xRX.jpg")
Thing.create(name: "Bulbasaur", image_url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png")
Thing.create(name: "The Smell of Old Books", image_url: "https://www.rd.com/wp-content/uploads/2017/04/01-Science-Has-Figured-Out-Why-You-Love-the-Smell-of-Old-Books-1024x683.jpg")
Thing.create(name: "The Angry Bee", image_url: "https://chriscander.com/wp-content/uploads/2013/06/The-Angry-Bee-2-3-13.jpg")

Thing.create(name: "Old, Splintery Playgrounds", image_url: "https://i.redd.it/q3cnn2u7vsyz.jpg")
Thing.create(name: "Altoids Sours", image_url: "https://i.redd.it/v2f61850hu4z.jpg")
Thing.create(name: "French Toast Crunch", image_url: "https://images-na.ssl-images-amazon.com/images/I/91PMaNt6ygL._SL1500_.jpg")
Thing.create(name: "The Song That Never Ends", image_url: "http://static.tvtropes.org/pmwiki/pub/images/lamb_chops_play_along_9159.jpg")
Thing.create(name: "Jurassic Bark", image_url: "https://i.kinja-img.com/gawker-media/image/upload/s--_1Y17cal--/c_scale,fl_progressive,q_80,w_800/dly0r1buradgq7n9fh1x.jpg")
Thing.create(name: "Quokkas", image_url: "http://www.traveller.com.au/content/dam/images/g/u/n/q/h/0/image.related.articleLeadwide.620x349.gunpvd.png/1488330286332.png")
Thing.create(name: "Toto - Africa", image_url: "https://img.discogs.com/y3nzPu7A4dDk2IX3rRfgcKsqXPc=/fit-in/600x599/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-649200-1295890139.jpeg.jpg")
Thing.create(name: "Stranger Things", image_url: "https://upload.wikimedia.org/wikipedia/commons/3/38/Stranger_Things_logo.png")
Thing.create(name: "Burt Blyleven", image_url: "https://baseballhall.org/sites/default/files/styles/fullscreen_image_popup/public/islandora_images/Blyleven%20Bert%202637_2000_Act_NBLPilling.jpg?itok=kZguIQuu")
Thing.create(name: "Shrek as a Human", image_url: "https://78.media.tumblr.com/d083d4545eac9f3a70c4e7cb7f478e22/tumblr_inline_oyv6sm6acp1qcuocg_540.png")

Thing.create(name: "TGI Fridays Times Square", image_url: "http://midtownlunch.com/files/2012/08/tgi.jpg")
Thing.create(name: "Pasqually P Pieplate", image_url: "https://vignette.wikia.nocookie.net/showbizpizza/images/e/e5/Pasqually_lg.jpg")
Thing.create(name: "The Circle Game", image_url: "https://pbs.twimg.com/media/C57301cWgAEuhR-.jpg")
Thing.create(name: "John C Calhoun", image_url: "https://www.biography.com/.image/t_share/MTE4MDAzNDEwMTYyOTEwNzM0/john-c-calhoun-37250-2-402.jpg")
Thing.create(name: "Wedge Antilles", image_url: "https://lumiere-a.akamaihd.net/v1/images/databank_wedgeantilles_01_169_b8185dce.jpeg")
Thing.create(name: "PaRappa the Rapper", image_url: "https://apollo2.dl.playstation.net/cdn/UP9000/CUSA01555_00/FREE_CONTENTumcfQRgkuE9WyBdR13q6/PREVIEW_SCREENSHOT1_105143.jpg")
Thing.create(name: "Libel", image_url: "https://1.bp.blogspot.com/-SrfH1gC3Mts/VvAAEIGWdzI/AAAAAAAABWk/n4yQd2JzCu0uUuXoSQXBeMLrIiiVNlVBA/s1600/libel.jpg")
Thing.create(name: "Milky Chance", image_url: "http://www.festivalpedralbes.com/wp-content/uploads/2016/04/Milky-Chance-web-Ok.jpg")
Thing.create(name: "Wishbone the Dog", image_url: "https://img.cuteness.com/cute-article-grid/cuteness/s3fs-public/1473972384396mceclip0.jpg")
Thing.create(name: "Sneezing Really Loud", image_url: "https://cdn.images.express.co.uk/img/dynamic/130/590x/sneezing-loudly-reasons-health-questions-821735.jpg")

Thing.create(name: "Beef", image_url: "https://upload.wikimedia.org/wikipedia/commons/6/60/Standing-rib-roast.jpg")
Thing.create(name: "Johann", image_url: "https://pbs.twimg.com/profile_images/679965501271990272/jl6_A6ZX.jpg")
Thing.create(name: "The 'Ooh wah ah ah ah' part of Down With the Sickness", image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/6/60/Disturbed_down_with_the_sickness.png/220px-Disturbed_down_with_the_sickness.png")
Thing.create(name: "Being the First to Use a Jar of Peanut Butter", image_url: "http://i.imgur.com/YmVAqbh.jpg")
Thing.create(name: "Saying 'Gif' instead of 'Gif'", image_url: "http://cdn.playbuzz.com/cdn/e335b131-0039-4540-8211-e4b9f971ee77/feea22d9-e6fd-4599-9551-50e5f69520b8.jpg")
Thing.create(name: "Koala Cookies", image_url: "https://i5.walmartimages.com/asr/84685211-848e-4984-8106-f1984099aaa2_1.53890c7dc69c5822c7d99f3765b7d6f2.jpeg")
Thing.create(name: "Good King Wenceslas", image_url: "http://www.cyberhymnal.org/img/w/e/wenceslas.jpg")
Thing.create(name: "Metro Station's 'Shake It'", image_url: "https://i.ytimg.com/vi/_wjFahULCK8/maxresdefault.jpg")
Thing.create(name: "The Mummy (with Brendan Frasier)", image_url: "https://static.highsnobiety.com/wp-content/uploads/2016/12/15173552/brendan-fraser-the-mummy-reboot-02.jpg")
Thing.create(name: "Car Phones", image_url: "https://www.endurancewarranty.com/learning-center/wp-content/uploads/2015/04/1980-car-phone-vintage-throwback.jpg")

Thing.create(name: "Throwing Pencils in the Ceiling", image_url: "https://hbr.org/resources/images/article_assets/hbr/1206/R1206E_EKBERG.jpg")
Thing.create(name: "Samurai Pizza Cats", image_url: "https://d1m6vmmwsgiy3l.cloudfront.net/images/screenshots/screenshot_1_21226.jpg")
Thing.create(name: "Porgs", image_url: "https://i.kinja-img.com/gawker-media/image/upload/s--a2PFWe9D--/c_fill,fl_progressive,g_north,h_264,q_80,w_470/w484fal4okv5pdcvmhjm.jpg")
Thing.create(name: "Meatloaf (singer)", image_url: "https://i.pinimg.com/736x/bb/9a/5f/bb9a5f29fdb3120ef0b586afdf505803--meatloaf-singer-meat-loaf.jpg")
Thing.create(name: "Pinot Noir (song)", image_url: "https://www.hypable.com/wp-content/uploads/2015/03/unbreakable-kimmy-schmidt-theme-song-pinot-noir.jpg")
Thing.create(name: "Kevin Smith's Shorts", image_url: "http://i0.kym-cdn.com/photos/images/original/001/081/388/616.png")
Thing.create(name: "Wet Subway Seats", image_url: "https://bloximages.newyork1.vip.townnews.com/columbiachronicle.com/content/tncms/assets/v3/editorial/7/3c/73c09c56-b5fd-11e7-a24b-4bf2ca11895f/59eaa0512283c.image.jpg")
Thing.create(name: "This Poster I Made", image_url: "https://static1.squarespace.com/static/53e24c25e4b0d57d9dae2d52/53e26c67e4b0b1602f1b593c/53e26c89e4b074733f290111/1407347851503/Brennan_Artcrank.png")
Thing.create(name: "Holiday Club, Chicago", image_url: "https://www.chibarproject.com/Reviews/HolidayClub/HolidayClubExteriorRK.jpg")
Thing.create(name: "Extreme Ironing", image_url: "https://lph5i1b6c053kq7us26bdk75-wpengine.netdna-ssl.com/wp-content/uploads/2009/06/extreme-ironing.jpg")
